### ISSUE TITLE
'TypeError: (intermediate value) is not a function' when compiling

### ISSUE THREAD

**Issue by jimzrt** [kripken/sql.js#229]
When I compile via `emmake make` I get the following error:

 ```
emcc --memory-init-file 0 -O3 -s INLINING_LIMIT=50 -s RESERVED_FUNCTION_POINTERS=64 -s EXPORTED_FUNCTIONS=@exported_functions -s EXTRA_EXPORTED_RUNTIME_METHODS=@exported_runtime_methods c/extension-functions.bc c/sqlite3.bc --post-js js/api.js -o js/sql-optimized-raw.js ;\


/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
        ^
TypeError: (intermediate value) is not a function
    at new JS_Parse_Error (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
    at js_error (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
    at croak (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
    at token_error (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
    at unexpected (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
    at Object.semicolon (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
    at prog1 (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
    at simple_statement (/usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
    at /usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
    at /usr/lib/emscripten/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1297:32
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 2791, in <module>
    run()
  File "/usr/lib/emscripten/emcc.py", line 1846, in run
    optimizer.flush()
  File "/usr/lib/emscripten/emcc.py", line 239, in flush
    self.run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/usr/lib/emscripten/emcc.py", line 272, in run_passes
    just_concat=just_concat)
  File "/usr/lib/emscripten/tools/shared.py", line 2150, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/usr/lib/emscripten/tools/js_optimizer.py", line 568, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/lib/emscripten/tools/tempfiles.py", line 79, in run_and_clean
    return func()
  File "/usr/lib/emscripten/tools/js_optimizer.py", line 568, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/usr/lib/emscripten/tools/js_optimizer.py", line 511, in run_on_js
    assert proc.returncode == 0
AssertionError
make: *** [Makefile:24: js/sql-optimized-raw.js] Fehler 1
```

emscripten v.1.37.28
CoffeeScript version 2.1.1

**Comment by 3CE8D2BAC65BDD6AA9** [comment]
+1 I have the same problem.
CoffeeScript version 1.10.0
emcc 1.37.35
I typed "make" and got the same error.  Any idea how to resolve it?
