### ISSUE TITLE
how to resolve this error in IE?

### ISSUE THREAD

**Issue by muthumech23** [kripken/sql.js#238]
SCRIPT5022: abort("Assertion failed: this is a legacy browser, build with LEGACY_VM_SUPPORT") at Error: 0
   at jsStackTrace (http://localhost:8023/starbucks/js/sql.js:1055:7)
   at stackTrace (http://localhost:8023/starbucks/js/sql.js:1070:3)
   at abort (http://localhost:8023/starbucks/js/sql.js:403067:3)
   at assert (http://localhost:8023/starbucks/js/sql.js:453:5)
   at Anonymous function (http://localhost:8023/starbucks/js/sql.js:1332:1)
   at Global code (http://localhost:8023/starbucks/js/sql.js:2:1)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by lovasoa** [comment]
The error tells you to build with LEGACY_VM_SUPPORT. Add it to the makefile. But I don't think you will get something usable in old browsers. sql.js is already quite slow in recent browsers
