### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by NeeEoo** [kripken/sql.js#245]
LLVM version 3.5

```java
NeeEoo@DESKTOP-CJEM7TB:/mnt/c/Users/NeeEoo/Downloads/sql.js-master$ make
emcc --memory-init-file 0 -O3 -s INLINING_LIMIT=50 -s RESERVED_FUNCTION_POINTERS=64 -s EXPORTED_FUNCTIONS='["_malloc","_free","_sqlite3_open","_sqlite3_exec","_sqlite3_free","_sqlite3_errmsg","_sqlite3_changes","_sqlite3_prepare_v2","_sqlite3_bind_text","_sqlite3_bind_blob","_sqlite3_bind_double","_sqlite3_bind_int","_sqlite3_bind_parameter_index","_sqlite3_step","_sqlite3_data_count","_sqlite3_column_double","_sqlite3_column_text","_sqlite3_column_blob","_sqlite3_column_bytes","_sqlite3_column_type","_sqlite3_column_name","_sqlite3_reset","_sqlite3_clear_bindings","_sqlite3_finalize","_sqlite3_close_v2","_sqlite3_create_function_v2","_sqlite3_value_bytes","_sqlite3_value_type","_sqlite3_value_text","_sqlite3_value_int","_sqlite3_value_blob","_sqlite3_value_double","_sqlite3_result_double","_sqlite3_result_null","_sqlite3_result_text","_RegisterExtensionFunctions"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap","stackAlloc","stackSave","stackRestore"]' c/extension-functions.bc c/sqlite3.bc --post-js js/api.js -o js/sql-optimized-raw.js ;\

WARNING  root: Assigning a non-existent settings attribute "EXTRA_EXPORTED_RUNTIME_METHODS"
WARNING  root:  - did you mean one of ORIGINAL_EXPORTED_FUNCTIONS, EXPORTED_FUNCTIONS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())```

**Comment by kripken** [comment]
Probably the emcc version is too old (before that `EXTRA_EXPORTED_RUNTIME_METHODS` option was added).

**Comment by NeeEoo** [comment]
Yep that was it apparently the ubuntu apt-get version was installed
But now i get this error
```java
NeeEoo@DESKTOP-CJEM7TB:/mnt/c/Users/NeeEoo/Downloads/sql.js-master$ make
emcc --memory-init-file 0 -O3 -s INLINING_LIMIT=50 -s RESERVED_FUNCTION_POINTERS=64 -s EXPORTED_FUNCTIONS='["_malloc","_free","_sqlite3_open","_sqlite3_exec","_sqlite3_free","_sqlite3_errmsg","_sqlite3_changes","_sqlite3_prepare_v2","_sqlite3_bind_text","_sqlite3_bind_blob","_sqlite3_bind_double","_sqlite3_bind_int","_sqlite3_bind_parameter_index","_sqlite3_step","_sqlite3_data_count","_sqlite3_column_double","_sqlite3_column_text","_sqlite3_column_blob","_sqlite3_column_bytes","_sqlite3_column_type","_sqlite3_column_name","_sqlite3_reset","_sqlite3_clear_bindings","_sqlite3_finalize","_sqlite3_close_v2","_sqlite3_create_function_v2","_sqlite3_value_bytes","_sqlite3_value_type","_sqlite3_value_text","_sqlite3_value_int","_sqlite3_value_blob","_sqlite3_value_double","_sqlite3_result_double","_sqlite3_result_null","_sqlite3_result_text","_RegisterExtensionFunctions"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap","stackAlloc","stackSave","stackRestore"]' c/extension-functions.bc c/sqlite3.bc --post-js js/api.js -o js/sql-optimized-raw.js ;\


INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/home/NeeEoo/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc.bc... (this will be cached in "/home/NeeEoo/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: wasm-libc.bc... (this will be cached in "/home/NeeEoo/.emscripten_cache/asmjs/wasm-libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: libc-extras.bc... (this will be cached in "/home/NeeEoo/.emscripten_cache/asmjs/libc-extras.bc" for subsequent builds)
INFO:root: - ok
warning: Linking two modules of different data layouts: '/home/NeeEoo/.emscripten_cache/asmjs/dlmalloc.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas 'c/extension-functions.bc' is 'e-p:32:32-i64:64'

warning: Linking two modules of different target triples: /home/NeeEoo/.emscripten_cache/asmjs/dlmalloc.bc' is 'asmjs-unknown-emscripten' whereas 'c/extension-functions.bc' is 'le32-unknown-nacl'

warning: Linking two modules of different data layouts: '/home/NeeEoo/.emscripten_cache/asmjs/libc.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas 'c/extension-functions.bc' is 'e-p:32:32-i64:64'

warning: Linking two modules of different target triples: /home/NeeEoo/.emscripten_cache/asmjs/libc.bc' is 'asmjs-unknown-emscripten' whereas 'c/extension-functions.bc' is 'le32-unknown-nacl'

warning: Linking two modules of different data layouts: '/home/NeeEoo/.emscripten_cache/asmjs/wasm-libc.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas 'c/extension-functions.bc' is 'e-p:32:32-i64:64'

warning: Linking two modules of different target triples: /home/NeeEoo/.emscripten_cache/asmjs/wasm-libc.bc' is 'asmjs-unknown-emscripten' whereas 'c/extension-functions.bc' is 'le32-unknown-nacl'

warning: Linking two modules of different data layouts: '/home/NeeEoo/.emscripten_cache/asmjs/libc-extras.bc' is 'e-p:32:32-i64:64-v128:32:128-n32-S128' whereas 'c/extension-functions.bc' is 'e-p:32:32-i64:64'

warning: Linking two modules of different target triples: /home/NeeEoo/.emscripten_cache/asmjs/libc-extras.bc' is 'asmjs-unknown-emscripten' whereas 'c/extension-functions.bc' is 'le32-unknown-nacl'

INFO:root:generating system asset: generated_struct_info.json... (this will be cached in "/home/NeeEoo/.emscripten_cache/asmjs/generated_struct_info.json" for subsequent builds)
INFO:root: - ok
warning: incorrect target triple 'le32-unknown-nacl' (did you use emcc/em++ on all source files and not clang directly?)
LLVM ERROR: Invalid SIMD cast between items of different bit sizes!
Traceback (most recent call last):
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emcc.py", line 3042, in <module>
    sys.exit(run())
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emcc.py", line 1759, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/tools/shared.py", line 2274, in emscripten
    emscripten._main(cmdline)
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emscripten.py", line 2222, in _main
    return temp_files.run_and_clean(lambda: main(
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emscripten.py", line 2227, in <lambda>
    DEBUG=DEBUG,
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emscripten.py", line 2153, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emscripten.py", line 81, in emscript
    backend_output = compile_js(infile, temp_files, DEBUG)
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/emscripten.py", line 110, in compile_js
    jsrun.timeout_run(subprocess.Popen(backend_args, stdout=subprocess.PIPE, universal_newlines=True), note_args=backend_args)
  File "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/emscripten/1.38.11/tools/jsrun.py", line 20, in timeout_run
    raise Exception('Subprocess "' + ' '.join(note_args) + '" failed with exit code ' + str(proc.returncode) + '!')
Exception: Subprocess "/mnt/c/Users/NeeEoo/Documents/emscripten/emsdk/clang/e1.38.11_64bit/llc /tmp/tmpA5t4BV/sql-optimized-raw.bc -march=js -filetype=asm -o /tmp/tmplLwx7S.4.js -emscripten-stack-size=5242880 -O3 -emscripten-precise-f32 -emscripten-reserved-function-pointers=64 -emscripten-global-base=1024 -emscripten-no-exit-runtime -emscripten-wasm -emscripten-only-wasm" failed with exit code 1!
Makefile:24: recipe for target 'js/sql-optimized-raw.js' failed
make: *** [js/sql-optimized-raw.js] Error 1```

**Comment by NeeEoo** [comment]
Yep, that was it. Thank you!
