### ISSUE TITLE
Feature Request: Handling JS Date variables

### ISSUE THREAD

**Issue by pupudu** [kripken/sql.js#334]
First of all, thanks for creating/maintaining this amazing library. I'll cut into my request. 

#### Background
I am using sql.js with typeorm to do integration testing rather than spinning up a mysql service for that. 

#### Issue
I noted that if I use Javascript `Date` objects in the where conditions, it works in production, but fails in tests, because sql.js doesn't convert the dates similar to how node-mysql driver does that.

#### Expectation
I would love it if sql.js would convert the dates correctly. 
For example, take the following example:

```ts
const updatedAt = new Date(/*Some date string goes here*/);

// Assume db is setup correctly as explained in ReadMe
db.run("SELECT * FROM test_table WHERE example_column = ?", [updatedAt]);
```

Now, this fails because sql.js would call `updatedAt.toString()`. But AFAIK, in node-mysql they call `updatedAt.toISOString()` (or some valid date string) internally. 

#### Notes
1. Code works with sql.js when we do `updatedAt.toISOString()` explicitly
2. The error that's being thrown at the moment is:
```bash
QueryFailedError: Wrong API use : tried to bind a value of an unknown type (Fri Jan 11 2019 01:01:01 GMT+1100 (Australian Eastern Daylight Time)).

    at new QueryFailedError (/Users/pubudu/Projects/typeorm-test/src/error/QueryFailedError.ts:9:9)
    at SqljsQueryRunner.<anonymous> (/Users/pubudu/Projects/typeorm-test/src/driver/sqljs/SqljsQueryRunner.ts:79:22)
```

**Comment by lovasoa** [comment]
This would be a useful feature. Pull requests are welcome!

**Comment by vagusX** [comment]
Just wonder would @lovasoa complete this?
